//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 11:56:05 AM IST 
//


package in.gov.nvli.harvester.customised;

import in.gov.nvli.harvester.custom.harvester_enum.HarRecordMetadataType;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for IdentifyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="repositoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="protocolVersion" type="{http://www.openarchives.org/OAI/2.0/}protocolVersionType"/>
 *         &lt;element name="adminEmail" type="{http://www.openarchives.org/OAI/2.0/}emailType" maxOccurs="unbounded"/>
 *         &lt;element name="earliestDatestamp" type="{http://www.openarchives.org/OAI/2.0/}UTCdatetimeType"/>
 *         &lt;element name="deletedRecord" type="{http://www.openarchives.org/OAI/2.0/}deletedRecordType"/>
 *         &lt;element name="granularity" type="{http://www.openarchives.org/OAI/2.0/}granularityType"/>
 *         &lt;element name="compression" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.openarchives.org/OAI/2.0/}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


@XmlRootElement(name = "Identify")
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "IdentifyType", propOrder = {
//    "repositoryName",
//    "baseURL",
//    "protocolVersion",
//    "adminEmail",
//    "earliestDatestamp",
//    "deletedRecord",
//    "granularity",
//    "compression",
//    "description"
//})
public class IdentifyTypeCustomised {

    protected String repositoryName;
    protected String baseURL;
    protected String protocolVersion;
    protected List<String> adminEmail;
    protected String earliestDatestamp;
    protected String deletedRecord;
    protected String granularity;
    protected List<String> compression;
    protected String description;
    protected Map<HarRecordMetadataType, Boolean> supportedMetadataTypes = new HashMap<>();
    
    
    
    
    public String getRepositoryName() {
        return repositoryName;
    }

    public void setRepositoryName(String repositoryName) {
        this.repositoryName = repositoryName;
    }

    public String getBaseURL() {
        return baseURL;
    }

    public void setBaseURL(String baseURL) {
        this.baseURL = baseURL;
    }

    public String getProtocolVersion() {
        return protocolVersion;
    }

    public void setProtocolVersion(String protocolVersion) {
        this.protocolVersion = protocolVersion;
    }

    public List<String> getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(List<String> adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getEarliestDatestamp() {
        return earliestDatestamp;
    }

    public void setEarliestDatestamp(String earliestDatestamp) {
        this.earliestDatestamp = earliestDatestamp;
    }

    public String getDeletedRecord() {
        return deletedRecord;
    }

    public void setDeletedRecord(String deletedRecord) {
        this.deletedRecord = deletedRecord;
    }

    public String getGranularity() {
        return granularity;
    }

    public void setGranularity(String granularity) {
        this.granularity = granularity;
    }

    public List<String> getCompression() {
        return compression;
    }

    public void setCompression(List<String> compression) {
        this.compression = compression;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Map<HarRecordMetadataType, Boolean> getSupportedMetadataTypes() {
        return supportedMetadataTypes;
    }

    public void setSupportedMetadataTypes(Map<HarRecordMetadataType, Boolean> supportedMetadataTypes) {
        this.supportedMetadataTypes = supportedMetadataTypes;
    }
}